export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const INTERNAL_SERVER_STATUS_CODE = 500;
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const VALIDATE_SERVER_STATUS_CODE = 400;
export const BUSINESS_ERROR = "BUSINESS_ERROR";
